version: 2

updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/setup-node-pnpm"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"
