allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  sharp: true
  unrs-resolver: true

peerDependencyRules:
  allowedVersions:
    '@dnd-kit/core>react': '19'
    '@dnd-kit/core>react-dom': '19'
    '@dnd-kit/utilities>react': '19'
